import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Requirement={id:string;title:string;description:string;type:string;priority:string;status:string;confidence:number;sourceText:string;dependencies:string[]};
type Report={readiness:number;requirements:Requirement[];documents:{id:string;name:string;category:string;verificationStatus:string;extractedText:string}[];risk:string;riskReasons:string[];blockers:{title:string;chain:string[]}[];contradictions:{field:string;values:string[];action:string}[];recommendations:{action:string;impact:number;reason:string}[]};
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
const pages=['Dashboard','Opportunity Upload','Requirements','Evidence Vault','Readiness Report','Profile','Settings'];
const Pill=({v}:{v:string})=><span className={'pill '+v}>{v.replace('_',' ')}</span>;

function App(){
 const [page,setPage]=useState('Dashboard'),[report,setReport]=useState<Report|null>(null),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [profile,setProfile]=useState({name:'Aarav Kumar',degree:'B.Tech Computer Science',year:'3',cgpa:'8.6',skills:'React, Python, Figma'});
 const load=async(reset=false)=>{try{setError('');const r=await fetch(`${API}/api/v1/demo${reset?'/reset':''}`,{method:reset?'POST':'GET'});if(!r.ok)throw Error('API unavailable');const data=await r.json();setReport(data.report)}catch{setError('Could not reach the local API. Run npm.cmd run dev and retry.')}};
 useEffect(()=>{load()},[]);
 const resolve=async(id:string)=>{const r=await fetch(`${API}/api/v1/demo/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requirementId:id})});if(!r.ok)return setError('Action failed.');setReport((await r.json()).report);setMessage('Readiness recalculated from verified evidence.');};
 const extract=async()=>{if(notice.length<30)return setMessage('Paste at least 30 characters.');const r=await fetch(`${API}/api/v1/opportunities/extract`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:notice})});if(!r.ok)return setMessage('Extraction failed.');const extracted=await r.json();setReport(old=>old?{...old,requirements:extracted.requirements}:old);setMessage('Requirements extracted and ready for review.');setPage('Requirements');};
 if(!report)return <div className="loading"><b>ApplyReady AI</b><p>{error||'Preparing your workspace…'}</p>{error&&<button onClick={()=>load()}>Retry</button>}</div>;
 const completed=report.requirements.filter(x=>x.status==='completed').length, action=report.recommendations[0], filtered=report.requirements.filter(x=>x.title.toLowerCase().includes(search.toLowerCase()));
 const Header=({title,sub}:{title:string;sub:string})=><header><div><p className="eyebrow">APPLICATION WORKSPACE</p><h1>{title}</h1><p className="muted">{sub}</p></div><button className="outline" onClick={()=>load(true)}>Reset demo</button></header>;
 const Dashboard=()=> <><Header title="National Student Innovation Hackathon" sub="Closes 15 August 2026 · 18 days remaining"/><section className="hero"><div><p className="eyebrow">READINESS SCORE</p><div className="score"><strong>{report.readiness}</strong><span>%</span></div><p className="muted">{completed} of {report.requirements.length} verified</p></div><div className="risk"><b>● {report.risk} deadline risk</b><p>{report.riskReasons.join(' ')}</p><div className="meter"><i style={{width:`${report.readiness}%`}}/></div></div><div className="next"><p className="eyebrow">NEXT BEST ACTION</p><b>{action?.action||'Ready to submit'}</b><p>{action?.reason}</p>{action&&<button onClick={()=>resolve(action.action.includes('transcript')?'transcript':'endorsement')}>Resolve now →</button>}</div></section><section className="metrics"><div><b>{completed}</b><span>Completed</span></div><div><b>{report.requirements.filter(x=>x.status==='missing').length}</b><span>Missing documents</span></div><div><b>{report.blockers.length}</b><span>Critical blockers</span></div><div><b>18</b><span>Days remaining</span></div></section><section className="two"><article className="card"><h2>Opportunity timeline</h2>{report.requirements.map(x=><div className="row" key={x.id}><span className={'dot '+x.status}/><div><b>{x.title}</b><p>{x.type} · {Math.round(x.confidence*100)}% confidence</p></div><Pill v={x.status}/></div>)}</article><article className="card"><h2>Dependency preview</h2><p>Approval workflow is the current critical path.</p><div className="graph">Tutor → HOD → Principal → Seal</div><h2>Recent activity</h2><div className="activity"><b>Evidence check complete</b><p>Resume and identity card verified.</p></div></article></section></>;
 const Upload=()=> <><Header title="Upload opportunity" sub="Paste a notice to create a structured requirement list."/><section className="card form"><label>Opportunity notice text<textarea value={notice} onChange={e=>setNotice(e.target.value)} placeholder="Paste a hackathon, internship, or scholarship notice…"/></label><p className="muted">Text extraction is active. PDF, image, and URL import will be available with the connected document provider.</p><button onClick={extract}>Extract requirements →</button></section></>;
 const Requirements=()=> <><Header title="Requirements" sub="Source-linked, confidence-aware application requirements."/><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search requirements"/><span>{filtered.length} items</span></div>{filtered.map(x=><article className="card req" key={x.id}><div><Pill v={x.status}/><h2>{x.title}</h2><p>{x.description}</p><div className="tags"><span>{x.priority} priority</span><span>{x.type}</span><span>{Math.round(x.confidence*100)}% confidence</span></div></div><aside><b>Source & dependencies</b><p>{x.sourceText}</p><small>{x.dependencies.length?x.dependencies.join(' → '):'No dependencies'}</small>{x.status!=='completed'&&<button onClick={()=>resolve(x.id==='transcript'?'transcript':'endorsement')}>Take action</button>}</aside></article>)}</>;
 const Vault=()=> <><Header title="Evidence vault" sub="Evidence is matched only when a verified document is present."/><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search documents"/><button onClick={()=>resolve('transcript')}>+ Add transcript</button></div><section className="docgrid">{report.documents.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(x=><article className="card document" key={x.id}><span>▣</span><h2>{x.name}</h2><p>{x.category}</p><Pill v={x.verificationStatus}/><small>{x.extractedText}</small></article>)}</section></>;
 const Readiness=()=> <><Header title="Readiness report" sub="A decision-ready map of evidence, risk, blockers, and recommendations."/><section className="report"><div className="ring"><b>{report.readiness}%</b><span>ready</span></div><div><h2>Evidence-backed readiness</h2><p>Critical documents and approvals receive the most weight. Nothing is marked complete from a weak inference.</p><div className="bars"><span>Eligibility<i style={{width:'100%'}}/></span><span>Documents<i style={{width:report.requirements.some(x=>x.id==='transcript'&&x.status==='completed')?'100%':'40%'}}/></span><span>Approvals<i style={{width:report.blockers.length?'15%':'100%'}}/></span></div></div></section><section className="two">{report.blockers.length>0&&<article className="card blocker"><p className="eyebrow">HIDDEN BLOCKER</p><h2>{report.blockers[0].title}</h2><div className="graph">{report.blockers[0].chain.join(' → ')}</div><button onClick={()=>resolve('endorsement')}>Start workflow</button></article>}<article className="card"><h2>Recommendations</h2>{report.recommendations.map(x=><div className="activity" key={x.action}><b>{x.action} <em>+{x.impact}%</em></b><p>{x.reason}</p></div>)}<button onClick={()=>window.print()}>Download / print report</button></article></section>{report.contradictions.map(x=><article className="card review" key={x.field}><b>{x.field} needs review</b><p>{x.values.join(' vs ')}. {x.action}</p></article>)}</>;
 const Profile=()=> <><Header title="Profile" sub="Maintain trusted facts for accurate matching."/><section className="card form profileform">{Object.entries(profile).map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setProfile({...profile,[k]:e.target.value})}/></label>)}<b>Profile completeness: 88%</b><div className="meter"><i style={{width:'88%'}}/></div><button onClick={()=>setMessage('Profile saved locally for this demo.')}>Save profile</button></section></>;
 const Settings=()=> <><Header title="Settings" sub="Account preferences and demo controls."/><section className="settings"><article className="card"><h2>AI provider</h2><p><Pill v="verified"/> Deterministic demo mode. API keys remain server-side.</p></article><article className="card"><h2>Notifications</h2><p>Deadline and evidence reminders enabled.</p><button onClick={()=>setMessage('Notification preference saved.')}>Manage</button></article><article className="card"><h2>Theme</h2><p>Light theme selected for the demo.</p><button onClick={()=>setMessage('Theme controls are coming with the next UI release.')}>Theme preference</button></article></section></>;
 const view=page==='Dashboard'?<Dashboard/>:page==='Opportunity Upload'?<Upload/>:page==='Requirements'?<Requirements/>:page==='Evidence Vault'?<Vault/>:page==='Readiness Report'?<Readiness/>:page==='Profile'?<Profile/>:<Settings/>;
 return <div className="shell"><aside><div className="brand">✦ ApplyReady <small>AI</small></div><p className="tag">Application readiness,<br/>not just summaries.</p>{pages.map(x=><button className={'nav '+(page===x?'active':'')} onClick={()=>{setPage(x);setSearch('')}} key={x}>{x}</button>)}<div className="profile"><div className="avatar">AK</div><div><b>{profile.name}</b><small>{profile.degree} · Year {profile.year}</small></div></div></aside><main>{message&&<div className="toast">{message}<button onClick={()=>setMessage('')}>×</button></div>}{error&&<div className="error">{error}</div>}{view}</main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
